// Generated by scripts/extract_cushion_segments.py -- do not edit by hand.
// Real cushion nose boundaries, read from the table model's own "Baize"
// nose mesh vertices at ball-center height (see that script's docstring).
// Both cover only the non-negative half of their rail (each is symmetric
// about its own center); safe_half_width()/safe_half_length() below take
// an abs_* coordinate. Piecewise linear between points.

// Long rails (left/right): [z, abs_x].
pub const CUSHION_BOUNDARY: &[[f32; 2]] = &[
    [0.052, 0.8865],
    [0.053, 0.8867],
    [0.054, 0.8823],
    [0.056, 0.877],
    [0.059, 0.8709],
    [0.063, 0.8642],
    [0.068, 0.8574],
    [0.069, 0.8576],
    [0.075, 0.8507],
    [0.083, 0.8445],
    [0.093, 0.8391],
    [0.104, 0.8348],
    [0.105, 0.835],
    [0.117, 0.832],
    [0.118, 0.8322],
    [0.132, 0.831],
    [1.617, 0.831],
    [1.629, 0.8317],
    [1.639, 0.8338],
    [1.64, 0.8336],
    [1.649, 0.8368],
    [1.65, 0.8366],
    [1.659, 0.8406],
    [1.667, 0.8454],
    [1.675, 0.8508],
    [1.682, 0.8568],
    [1.689, 0.8631],
    [1.693, 0.8892],
    [1.694, 0.8881],
    [1.703, 0.8888],
    [1.704, 0.8881],
    [1.712, 0.8881],
    [1.784, 0.8892],
];

// Short rails (baulk/top): [x, abs_z].
pub const SHORT_RAIL_BOUNDARY: &[[f32; 2]] = &[
    [0.722, 1.726],
    [0.733, 1.727],
    [0.744, 1.729],
    [0.754, 1.732],
    [0.763, 1.736],
    [0.772, 1.741],
    [0.78, 1.746],
    [0.787, 1.752],
    [0.794, 1.758],
    [0.799, 1.784],
    [0.889, 1.784],
];
